"""Tek tek kontrol edilen başlangıç yazıları; tüm sitenin otomatik onayı değil."""
# Tarihler yayıncı metaverisinden alınır. Bilinmeyen tarihe bugünü atamayız.
LIBRARY_ITEMS = (
    dict(topic="yemek", title="Padrón Biberi Nedir? Nasıl Tüketilir?",
         url="https://yemek.com/padron-biberi/", source_id="yemek-com", source_name="Yemek.com", publisher_id="yemek.com",
         published_at="2026-09-28T00:00:00+03:00", publication_date_only=True,
         recommendation_kind="timely", content_type="article",
         recommendation_reason="Bir malzemeyi tanıtan ve mutfakta kullanımını anlatan güncel bir yazı; tarifin arkasındaki yemek kültürünü keşfetmek için."),
    dict(topic="yemek", title="Mutfakta Kimyasal Reaksiyonlar Nelerdir?",
         url="https://www.kisikatesakademi.com.tr/blog/mutfakta-kimyasal-reaksiyonlar-nelerdir-1268",
         source_id="kisik-ates", source_name="Kısık Ateş Akademi", publisher_id="kisikatesakademi.com.tr",
         published_at="2024-11-22T13:54:47+03:00", recommendation_kind="foundation", content_type="blog",
         recommendation_reason="Pişirirken renk, doku ve lezzetin neden değiştiğini açıklayan mutfak bilimi yazısı. Temel pişirme süreçleri için seçildi."),
    dict(topic="moda", title="2026 Pre-Fall Stil Rehberi",
         url="https://vogue.com.tr/moda/2026-pre-fall-stil-rehberi", source_id="vogue-tr", source_name="Vogue Türkiye", publisher_id="vogue.com.tr",
         published_at="2026-08-22T00:00:00+03:00", publication_date_only=True,
         recommendation_kind="timely", content_type="article",
         recommendation_reason="Sonbahara geçişte katmanlar, dokular ve kombin fikirleri; sezon bilgisi olduğu için güncellik sınırı uygulanır."),
    dict(topic="moda", title="Takım Elbise Rehberi: Kalıp, Kumaş, Renk ve Kombin Nasıl Seçilir?",
         url="https://sartoria.com.tr/takim-elbise-rehberi/", source_id="sartoria", source_name="Sartoria", publisher_id="sartoria.com.tr",
         published_at="2026-09-08T20:08:59+00:00", recommendation_kind="timely", content_type="blog",
         recommendation_reason="Kalıp ve kumaş farklarını anlamak için ayrıntılı bir rehber. Bir giyim markasının kendi blogunda yayımlanıyor."),
    dict(topic="kitap", title="“Önemli şeylerin bir dipnotu” olarak hayat",
         url="https://www.k24kitap.org/onemli-seylerin-bir-dipnotu-olarak-hayat-5866", source_id="k24", source_name="K24", publisher_id="k24kitap.org",
         published_at="2026-09-24T00:00:00+03:00", publication_date_only=True,
         recommendation_kind="timely", content_type="article",
         recommendation_reason="Arundhati Roy’un Sığınağım ve Fırtınam kitabını, anı ve roman ilişkisi üzerinden ele alan bir deneme."),
    dict(topic="kitap", title="Tarihi Değiştirmek: Haluk Erdemol’un “Kolomb’un Yumurtası” Eseri Üzerine | Cihad Özsöz",
         url="https://www.edebiyathaber.net/tarihi-degistirmek-haluk-erdemolun-kolombun-yumurtasi-eseri-uzerine-cihad-ozsoz/",
         source_id="edebiyat-inceleme", source_name="Edebiyat Haber", publisher_id="edebiyathaber.net",
         published_at="2026-09-30T03:34:00+00:00", recommendation_kind="timely", content_type="article",
         recommendation_reason="Bir eseri tarih ve anlatı açısından inceleyen yazı; kitap duyurusundan daha ayrıntılı bir okuma sunuyor."),
    dict(topic="spor", title="Magnus Etkisi: Falsolu Vuruşların Arka Planındaki Fizik",
         url="https://www.matematiksel.org/futbolun-arkasindaki-fizik-magnus-etkisi/",
         source_id="matematiksel", source_name="Matematiksel", publisher_id="matematiksel.org",
         published_at="2017-03-27T11:53:53+00:00", recommendation_kind="foundation", content_type="article",
         recommendation_reason="Mayıs 2026’da güncellenen bu anlatım, topun neden falso aldığını açıklıyor. Maç sonucu yerine sporun arkasındaki fizik için seçildi."),
    dict(topic="spor", title="Nasıl Daha Hızlı Koşulur?",
         url="https://www.decathlon.com.tr/c/prog/nasil-daha-hizli-kosulur_9013f9f2-6194-4fd7-994f-f0637b14dd52",
         source_id="decathlon-rehber", source_name="Decathlon / Spor rehberi", publisher_id="decathlon.com.tr",
         published_at=None, recommendation_kind="foundation", content_type="article",
         recommendation_reason="Koşu tekniği ve hazırlığın temel kavramlarını tanıtan rehber. Spor ürünleri satan yayıncının eğitim içeriği."),
    dict(topic="finans", title="Yatırım Fonları: Tanıtım Rehberi",
         url="https://www.spk.gov.tr/kurumlar/fonlar/yatirim-fonlari/menkul-kiymet-yatirim-fonlari/tanitim-rehberi",
         source_id="spk-egitim", source_name="Sermaye Piyasası Kurulu", publisher_id="spk.gov.tr",
         published_at=None, recommendation_kind="foundation", content_type="article",
         recommendation_reason="Fon, portföy ve katılma payı kavramlarını tanıtan resmi eğitim rehberi. Finans başlığında temel kavramları öğrenmek için seçildi."),
    dict(topic="finans", title="Bileşik faiz nedir?",
         url="https://www.ing.com.tr/tr/isiniz-icin/ingkobiblog/bilesik-faiz-nedir",
         source_id="ing-blog", source_name="ING / KOBİ Blog", publisher_id="ing.com.tr",
         published_at="2024-05-16T00:00:00+03:00", publication_date_only=True,
         recommendation_kind="foundation", content_type="blog",
         recommendation_reason="Bileşik faizin mantığını ve hesaplamasını açıklayan temel finans yazısı. Güncel faiz oranı önerisi için değil, kavramı öğrenmek için seçildi."),
    dict(topic="ekonomi", title="Ekonomi Yalnızca Ekonomi Değildir",
         url="https://www.mahfiegilmez.com/2026/09/ekonomi-yalnzca-ekonomi-degildir.html",
         source_id="mahfi-egilmez", source_name="Mahfi Eğilmez", publisher_id="mahfiegilmez.com",
         published_at="2026-09-21T00:00:00+03:00", publication_date_only=True,
         recommendation_kind="timely", content_type="blog",
         recommendation_reason="Beklentiler, güven ve kurumların ekonomik kararlarla ilişkisini ele alan makroekonomi değerlendirmesi."),
    dict(topic="kitap", title="Deneme Kurmacaya Değince | Yusuf Çopur",
         url="https://www.edebiyathaber.net/deneme-kurmacaya-degince-yusuf-copur/",
         source_id="edebiyat-inceleme", source_name="Edebiyat Haber", publisher_id="edebiyathaber.net",
         published_at="2026-09-15T00:00:00+03:00", publication_date_only=True,
         recommendation_kind="timely", content_type="article",
         recommendation_reason="Deneme ve öykü arasındaki sınırları yazarın kendi kitabı ve okur yorumları üzerinden tartışan edebiyat yazısı."),
)
